function colector_comun3(R1,R2,R3,b,Val,A,f,n)
fig=figure( ...
           'Name','  Colector Comun', ...
           'NumberTitle','off', ...
           'Units','Normalized',...
           'NumberTitle','off','color','k',...
           'Position',[0.08 0.08 0.9 0.8]);

subplot('Position',[0.01,0.2,0.3,0.6]);
img= imread('img1.jpg');
image(img);
axis off;
subplot('Position',[0.35,0.3,0.21,0.34]);
img2= imread('img2.jpg');
image(img2);
axis off;
subplot('Position',[0.65,0.3,0.29,0.34]);
img3= imread('img3.jpg');
image(img3);
axis off;
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.3 0.8 0.3 0.14],...
    'backgroundcolor','k',...
    'foregroundcolor','white',...
    'FontSize',20,...
    'FontWeight','bold',...
    'String','Conexiunea Colector Comun'); 

Bp=uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.385 0.22 0.16 0.05],...
    'String','Curent Continuu',...
    'FontSize',15,...
    'FontWeight','bold',...
    'Callback','curent_c'); 
Bp=uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.70 0.22 0.16 0.05],...
    'String','Semnal Mic',...
    'FontSize',15,...
    'FontWeight','bold',...
    'Callback','semnal_m')
uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.01 0.1 0.1 0.05],...
    'String','Inapoi',...
    'FontSize',15,...
    'FontWeight','bold',...
    'Callback','interfata_principala')
f=uimenu('Label','Documentatie');
uimenu(f,'Label','Documentatie','Callback','open(''Documentatie.pdf'')');
uimenu(f,'Label','PowerPoint','Callback','open(''Presentation.pdf'')',...
    'Separator','on');
uimenu(f,'Label','Close','Callback','close',...
    'Separator','on','Accelerator','Q');




