function curent_continuu(R1,R2,R3,beta,Val)
fig=figure( ...
           'Name','  Colector Comun', ...
           'NumberTitle','off', ...
           'Units','Normalized',...
           'NumberTitle','off','color','k',...
           'Position',[0.08 0.08 0.7 0.8]);

subplot('Position',[0.29,0.43,0.35,0.45]);
img= imread('img2.jpg');
image(img);
axis off;

Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.314 0.89 0.3 0.07],...
    'backgroundcolor','k',...
    'foregroundcolor','white',...
    'FontSize',15,...
    'FontWeight','bold',...
    'String','Curent Continuu'); 
group=uibuttongroup('Visible','on',...
                     'BackgroundColor','k',...
                     'ForegroundColor','white',...
                     'Title','VALORI',...
                     'FontSize',8,...
                     'FontAngle','italic',...
                     'FontWeight','bold',...
                     'TitlePosition','centertop',...
                     'Tag','radiobutton',...
                     'Position',[0.09 0.07 0.29 0.32]);
%primul buton
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.85 0.35 0.1],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' R1[Ohm]',...
    'FontWeight','Bold',...
    'Parent',group); 
 uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.85 0.35 0.1],...
                      'FontSize',8,...
                      'String',R1,...
                      'FontWeight','Bold',...
                      'Callback','R1=str2num(get(gco,''String''));close;curent_continuu(R1,R2,R3,beta,Val);',...
                      'Parent',group);
 %buton 2
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.7 0.35 0.1],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' R2[Ohm]',...
    'FontWeight','Bold',...
    'Parent',group);
 uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.7 0.35 0.1],...
                      'FontSize',8,...
                      'String',R2,...
                      'FontWeight','Bold',...
                      'Callback','R2=str2num(get(gco,''String''));close;curent_continuu(R1,R2,R3,beta,Val);',...
                      'Parent',group);
%buton 3
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.55 0.35 0.1],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' R3[Ohm]',...
    'FontWeight','Bold',...
    'Parent',group); 
 uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.55 0.35 0.1],...
                      'FontSize',8,...
                      'String',R3,...
                      'FontWeight','Bold',...
                      'Callback','R3=str2num(get(gco,''String''));close;curent_continuu(R1,R2,R3,beta,Val);',...
                      'Parent',group);
 %buton 4
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.4 0.35 0.1],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' Val[V]',...
    'FontWeight','Bold',...
    'Parent',group); 
uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.4 0.35 0.1],...
                      'FontSize',8,...
                      'String',Val,...
                      'FontWeight','Bold',...
                      'Callback','Val=str2num(get(gco,''String''));close;curent_continuu(R1,R2,R3,beta,Val);',...
                      'Parent',group);
%buton 5
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.25 0.35 0.12],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' BETA',...
    'FontWeight','Bold',...
    'Parent',group); 
uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.25 0.35 0.12],...
                      'FontSize',8,...
                      'String',beta,...
                      'FontWeight','Bold',...
                      'Callback','beta=str2num(get(gco,''String''));close;curent_continuu(R1,R2,R3,beta,Val);',...
                      'Parent',group);
Vbe=0.7;
Vb=(R2/(R1+R2))*Val;
Rb=(R1*R2)/(R1+R2);
Ib=(Vb-Vbe)/(Rb+(beta+1)*R3);
Ie=(beta+1)*Ib;
Ic=beta*Ib;
Vce=Val-Ie*R3;
if (Vb<0.7 || Vb>Val)
     clear all;
close all;
fig=figure( ...
           'Name',' Eroare', ...
           'NumberTitle','off', ...
           'Units','Normalized',...
           'NumberTitle','off','color','k',...
           'Position',[0.2 0.3 0.5 0.5]);
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.32 0.45 0.33 0.3],...
    'backgroundcolor','k',...
    'foregroundcolor','white',...
    'FontSize',15,...
    'FontWeight','bold',...
    'String','Valorile introduse nu sunt corecte '); 
uicontrol('Style','pushbutton',...
             'Units','normalized',...
             'Position',[0.01 0.89 0.1 0.06],...
             'FontWeight','bold',...
             'FontSize',14,...
             'foregroundColor','w',...
             'backgroundcolor','black',...
             'String','Inapoi',...
             'Callback','colector_comun3')

else
    
   

group2=uibuttongroup('Visible','on',...
                     'BackgroundColor','k',...
                     'ForegroundColor','white',...
                     'Title','VALORI CALCULATE',...
                     'FontSize',8,...
                     'FontAngle','italic',...
                     'FontWeight','bold',...
                     'TitlePosition','centertop',...
                     'Tag','radiobutton',...
                     'Position',[0.6 0.07 0.29 0.32]);
%primul buton
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.85 0.35 0.1],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' Vb[V]',...
    'FontWeight','Bold',...
    'Parent',group2); 
uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.85 0.35 0.1],...
                      'FontSize',8,...
                      'String',Vb,...
                      'FontWeight','Bold',...
                      'Callback','',...
                      'Parent',group2);
%buton 2
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.7 0.35 0.1],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' Rb[Ohm]',...
    'FontWeight','Bold',...
    'Parent',group2);
uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.7 0.35 0.1],...
                      'FontSize',8,...
                      'String',Rb,...
                      'FontWeight','Bold',...
                      'Callback','',...
                      'Parent',group2);
%buton 3
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.55 0.35 0.1],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' Ib[mA]',...
    'FontWeight','Bold',...
    'Parent',group2);
uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.55 0.35 0.1],...
                      'FontSize',8,...
                      'String',Ib,...
                      'FontWeight','Bold',...
                      'Callback','',...
                      'Parent',group2);
%buton 4
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.4 0.35 0.1],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' Ie[mA]',...
    'FontWeight','Bold',...
    'Parent',group2); 
uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.4 0.35 0.1],...
                      'FontSize',8,...
                      'String',Ie,...
                      'FontWeight','Bold',...
                      'Callback','',...
                      'Parent',group2);
%buton 5
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.25 0.35 0.12],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' Ic[mA]',...
    'FontWeight','Bold',...
    'Parent',group2); 
uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.25 0.35 0.1],...
                      'FontSize',8,...
                      'String',Ic,...
                      'FontWeight','Bold',...
                      'Callback','',...
                      'Parent',group2);
%buton 6
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.1 0.35 0.12],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' Vce[V]',...
    'FontWeight','Bold',...
    'Parent',group2); 
uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.1 0.35 0.1],...
                      'FontSize',8,...
                      'String',Vce,...
                      'FontWeight','Bold',...
                      'Callback','',...
                      'Parent',group2);

uicontrol('Style','pushbutton',...
             'Units','normalized',...
             'Position',[0.01 0.89 0.1 0.06],...
             'FontWeight','bold',...
             'FontSize',14,...
             'foregroundColor','w',...
             'backgroundcolor','black',...
             'String','Inapoi',...
             'Callback','colector_comun3')


end;
