clear all;
close all;
fig=figure( ...
           'Name','  Conexiunea Colector Comun', ...
           'NumberTitle','off', ...
           'Units','Normalized',...
           'NumberTitle','off','color','k',...
           'Position',[0.08 0.08 0.9 0.8]);
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.25 0.8 0.4 0.14],...
    'backgroundcolor','k',...
    'foregroundcolor','white',...
    'FontSize',21,...
    'FontWeight','bold',...
    'String',' CONEXIUNEA COLECTOR COMUN TRANZISTOR BIPOLAR')
Bp=uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.3 0.6 0.3 0.09],...
    'String','PROIECT',...
    'FontSize',21,...
    'FontWeight','bold',...
    'Callback','interfata3'); 
Bp=uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.3 0.2 0.3 0.09],...
    'FontSize',21,...
    'FontWeight','bold',...
    'String','DOCUMENTATIE',...
    'Callback','open(''Documentatie.pdf'')'); 
Bp=uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.3 0.4 0.3 0.09],...
    'FontSize',21,...
    'FontWeight','bold',...
    'String','PREZENTARE',...
    'Callback','open(''Presentation.pdf'')'); 


