function semnal_mic(A,f,n,R1,R2,R3,beta,Val,x)
fig=figure( ...
           'Name','  Colector Comun', ...
           'NumberTitle','off', ...
           'Units','Normalized',...
           'NumberTitle','off','color','w',...
           'Position',[0.08 0.08 0.7 0.8]);
subplot('Position',[0.02,0.43,0.42,0.45]);
img= imread('img5.jfif');
image(img);
axis off;
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.32 0.89 0.3 0.07],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'FontSize',15,...
    'FontWeight','bold',...
    'String','SCHEMA DE SEMNAL MIC'); 


group=uibuttongroup('Visible','on',...
                     'BackgroundColor','k',...
                     'ForegroundColor','white',...
                     'Title','VALORI',...
                     'FontSize',8,...
                     'FontAngle','italic',...
                     'FontWeight','bold',...
                     'TitlePosition','centertop',...
                     'Tag','radiobutton',...
                     'Position',[0.45 0.49 0.29 0.32]);
%primul buton
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.85 0.35 0.1],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' R1[Ohm]',...
    'FontWeight','Bold',...
    'Parent',group); 
 uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.85 0.35 0.1],...
                      'FontSize',8,...
                      'String',R1,...
                      'FontWeight','Bold',...
                      'Callback','R1=str2num(get(gco,''String''));close; semnal_mic(A,f,n,R1,R2,R3,beta,Val,x);',...
                      'Parent',group);
 %buton 2
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.7 0.35 0.1],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' R2[Ohm]',...
    'FontWeight','Bold',...
    'Parent',group);
 uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.7 0.35 0.1],...
                      'FontSize',8,...
                      'String',R2,...
                      'FontWeight','Bold',...
                      'Callback','R2=str2num(get(gco,''String''));close; semnal_mic(A,f,n,R1,R2,R3,beta,Val,x);',...
                      'Parent',group);
%buton 3
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.55 0.35 0.1],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' R3[Ohm]',...
    'FontWeight','Bold',...
    'Parent',group); 
 uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.55 0.35 0.1],...
                      'FontSize',8,...
                      'String',R3,...
                      'FontWeight','Bold',...
                      'Callback','R3=str2num(get(gco,''String''));close; semnal_mic(A,f,n,R1,R2,R3,beta,Val,x);',...
                      'Parent',group);
 %buton 4
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.4 0.35 0.1],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' Val[V]',...
    'FontWeight','Bold',...
    'Parent',group); 
uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.4 0.35 0.1],...
                      'FontSize',8,...
                      'String',Val,...
                      'FontWeight','Bold',...
                      'Callback','Val=str2num(get(gco,''String''));close; semnal_mic(A,f,n,R1,R2,R3,beta,Val,x);',...
                      'Parent',group);
%buton 5
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.25 0.35 0.12],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' BETA',...
    'FontWeight','Bold',...
    'Parent',group); 
uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.25 0.35 0.12],...
                      'FontSize',8,...
                      'String',beta,...
                      'FontWeight','Bold',...
                      'Callback','beta=str2num(get(gco,''String''));close; semnal_mic(A,f,n,R1,R2,R3,beta,Val,x);',...
                      'Parent',group);
group2=uibuttongroup('Visible','on',...
                     'BackgroundColor','k',...
                     'ForegroundColor','white',...
                     'Title','PARAMETRII SEMNAL',...
                     'FontSize',8,...
                     'FontAngle','italic',...
                     'FontWeight','bold',...
                     'TitlePosition','centertop',...
                     'Tag','radiobutton',...
                     'Position',[0.74 0.49 0.25 0.2]);
%primul buton
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.85 0.35 0.13],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' A',...
    'FontWeight','Bold',...
    'Parent',group2); 
 uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.85 0.35 0.13],...
                      'FontSize',8,...
                      'String',A,...
                      'FontWeight','Bold',...
                      'Callback','A=str2num(get(gco,''String''));close;semnal_mic(A,f,n,R1,R2,R3,beta,Val,x);',...
                      'Parent',group2);
 %buton 2
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.67 0.35 0.13],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' f',...
    'FontWeight','Bold',...
    'Parent',group2);
 uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.67 0.35 0.13],...
                      'FontSize',8,...
                      'String',f,...
                      'FontWeight','Bold',...
                      'Callback','f=str2num(get(gco,''String''));close;semnal_mic(A,f,n,R1,R2,R3,beta,Val,x);',...
                      'Parent',group2);
%buton 3
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.51 0.35 0.13],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' n',...
    'FontWeight','Bold',...
    'Parent',group2); 
 uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.51 0.35 0.13],...
                      'FontSize',8,...
                      'String',n,...
                      'FontWeight','Bold',...
                      'Callback','n=str2num(get(gco,''String''));close;semnal_mic(A,f,n,R1,R2,R3,beta,Val,x);',...
                      'Parent',group2);
Vbe=0.7;
Vb=(R2/(R1+R2))*Val;
Rb=(R1*R2)/(R1+R2);
Ib=(Vb-Vbe)/(Rb+(beta+1)*R3);
Ic=beta*Ib;
gm=40*Ic;
rbe=beta/gm;
Av=(gm*R3)/(1+(gm*R3));
Ri=(Rb*(rbe+(beta+1)*R3))/(Rb+(rbe+(beta+1)*R3));
Ro=(rbe*R3)/(rbe+R3);
if (Vb<0.7 || Vb>Val)
     clear all;
close all;
fig=figure( ...
           'Name',' Eroare', ...
           'NumberTitle','off', ...
           'Units','Normalized',...
           'NumberTitle','off','color','k',...
           'Position',[0.2 0.3 0.5 0.5]);
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.32 0.45 0.33 0.3],...
    'backgroundcolor','k',...
    'foregroundcolor','white',...
    'FontSize',15,...
    'FontWeight','bold',...
    'String','Valorile introduse nu sunt corecte '); 
uicontrol('Style','pushbutton',...
             'Units','normalized',...
             'Position',[0.01 0.89 0.1 0.06],...
             'FontWeight','bold',...
             'FontSize',14,...
             'foregroundColor','w',...
             'backgroundcolor','black',...
             'String','Inapoi',...
             'Callback','colector_comun3')

else
group3=uibuttongroup('Visible','on',...
                     'BackgroundColor','k',...
                     'ForegroundColor','white',...
                     'Title','VALORI CALCULATE',...
                     'FontSize',8,...
                     'FontAngle','italic',...
                     'FontWeight','bold',...
                     'TitlePosition','centertop',...
                     'Tag','radiobutton',...
                     'Position',[0.45 0.02 0.51 0.34]);
%primul buton
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.85 0.35 0.1],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' Av',...
    'FontWeight','Bold',...
    'Parent',group3); 
uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.85 0.35 0.1],...
                      'FontSize',8,...
                      'String',Av,...
                      'FontWeight','Bold',...
                      'Callback','',...
                      'Parent',group3);
%buton 2
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.7 0.35 0.1],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' gm',...
    'FontWeight','Bold',...
    'Parent',group3);
uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.7 0.35 0.1],...
                      'FontSize',8,...
                      'String',gm,...
                      'FontWeight','Bold',...
                      'Callback','',...
                      'Parent',group3);
%buton 3
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.55 0.35 0.1],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' rbe',...
    'FontWeight','Bold',...
    'Parent',group3);
uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.55 0.35 0.1],...
                      'FontSize',8,...
                      'String',rbe,...
                      'FontWeight','Bold',...
                      'Callback','',...
                      'Parent',group3);
%buton 4
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.4 0.35 0.1],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' Ri',...
    'FontWeight','Bold',...
    'Parent',group3); 
uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.4 0.35 0.1],...
                      'FontSize',8,...
                      'String',Ri,...
                      'FontWeight','Bold',...
                      'Callback','',...
                      'Parent',group3);
%buton 5
Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.25 0.35 0.12],...
    'backgroundcolor','w',...
    'foregroundcolor','black',...
    'String',' Ro',...
    'FontWeight','Bold',...
    'Parent',group3); 
uicontrol('Style','edit',...
                      'Units','normalized',...
                      'Position',[0.61 0.25 0.35 0.1],...
                      'FontSize',8,...
                      'String',Ro,...
                      'FontWeight','Bold',...
                      'Callback','',...
                      'Parent',group3);
T=1/f;
t=0:T/100:n*T;  

switch(x)
    case 1
          vi=A*sin(2*pi*f*t);
    case 2
        vi=(2*A/pi)*asin(sin(2*pi*f*t));
    case 3
        vi = A*sign(sin(2*pi*f*t));
end
vo=Av*vi;

subplot('position',[0.04 0.06 0.37 0.11] );%setam o fereastra de plotare 
plot(t,vi);
grid on;
title('V0');
xlabel('timp [s]');
ylabel('Amplitudine [V]');
subplot('position',[0.04 0.256 0.37 0.11] );%setam o fereastra de plotare 
plot(t,vo);
grid on;
title('Vi');
xlabel('timp [s]');
ylabel('Amplitudine [V]');
uicontrol('Style','pushbutton',...
             'Units','normalized',...
             'Position',[0.01 0.89 0.1 0.06],...
             'FontWeight','bold',...
             'FontSize',14,...
             'foregroundColor','w',...
             'backgroundcolor','black',...
             'String','Inapoi',...
             'Callback','colector_comun3')
uicontrol('Style','PopupMenu',...
          'Units','normalized',...
          'Position',[0.74 0.56 0.25 0.2],...
          'String','Sinusoidal|Triunghiular|Dreptunghiular',...
          'Value',x,...
          'FontSize',10,...
          'BackgroundColor','black',...
          'ForegroundColor','w',...
          'FontWeight','Bold',...
          'Callback','x=get(gco,''value''),close;semnal_mic(A,f,n,R1,R2,R3,beta,Val,x) ;')
end;
